version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
        node-version: 14.15.4
      - node/test
workflows:
    build-and-test:
      jobs:
        - build-and-test