version: 2.1
orbs:
  node: circleci/node@4.1.0

jobs:
  instal-node:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: 14.15.4
      
workflows:
  build-and-test:
    jobs:
      - instal-node
      - node/test