version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run:
                name: Swap node versions
                command: |
                  set +e
                  wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
                  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
                  nvm install v14
                  nvm alias default 14.15.4

                  echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
                  echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            - run: npm install
            - run: npm test
workflows:
    build-and-test:
      jobs:
        - build-and-test